[package]
edition = "2021"
name = "http-content-range"
version = "0.1.0"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
repository = "https://github.com/nyurik/http-content-range"
description = "HTTP Content Range response header parser"
license = "MIT OR Apache-2.0"
